package sbnz.reservation;

import pro.restommender.model.Reservation;
import pro.restommender.model.Rule;
import pro.restommender.dto.Search;

import java.util.List;

rule "Classify Discount - Level 0 - D1 - create X1"
  agenda-group "reservation-number-discount"
  when 
    // TODO: proveriti da li da ostavimo samo jednu liniju, ili ove 3, 
    // jer u uve tri koristimo napredne funkcije, a ova jedna je jednostavnija
    $r: Reservation ($user: user, $dis: discount)
    $rule: Rule(rule == "", fact == "")
    $rezervacije: List() from collect(Reservation() from $user.getReservations())
    eval($rezervacije.size() < 2)
    // $r: Reservation (user.getReservations().size() < 2)
  then 
    modify($r) {setDiscount($dis + 5)}
    modify($rule) {setRule("D1")}
    modify($rule) {setFact("X1")}
    System.out.println("reservation number lt 2");
end

rule "Classify Discount - Level 1 - D2 - Create X2"
  agenda-group "reservation-number-discount"
  when 
    // TODO: isto sto i gore
    $r: Reservation (user.getReservations().size() >= 2 && user.getReservations().size() < 4, $dis: discount)
    $rule: Rule(rule == "", fact == "")
  then 
    modify($r) {setDiscount($dis + 10)}
    modify($rule) {setRule("D2")}
    modify($rule) {setFact("X2")}
    System.out.println("reservation number between 2 and 4");
end




////////////////////////TODO: LEVEL 2 ispraviti kao i ovo gore

rule "Classify Discount - Level 2 - D3 - Create X3"
  agenda-group "reservation-number-discount"
  when 
    // TODO: isto sto i gore
    $r: Reservation (user.getReservations().size() >= 4, $dis: discount)
    $rule: Rule(rule == "", fact == "")
  then 
    modify($r) {setDiscount($dis + 15)}
    modify($rule) {setRule("D3")}
    modify($rule) {setFact("X3")}
    System.out.println("reservation number gt 4");
end

// Pravila drugog nivoa

rule "Classify Discount - number of persons lt 4 - D4, Create X4 - on X1"
  agenda-group "reservation-number-discount"
  no-loop
  when 
    $search: Search(numOfPersons < 4)
    $r: Reservation($discount: discount)
  then 
    modify($r) { setDiscount($discount + 2); }
end

rule "Classify Discount - number of persons is 4"
  agenda-group "reservation-number-discount"
  no-loop
  when 
    $search: Search(numOfPersons == 4)
    $r: Reservation($discount: discount)
  then 
    modify($r) { setDiscount($discount + 3); }
end

rule "Classify Discount - number of persons gt 4"
  agenda-group "reservation-number-discount"
  no-loop
  when 
    $search: Search(numOfPersons > 4)
    $r: Reservation($discount: discount)
  then 
    modify($r) { setDiscount($discount + 4); }
end

// Pravila treceg nivoa

// rule "Classify Discount - Level 1"
//   agenda-group "reservation-number-discount"
//   when 
//     // TODO: isto sto i gore
//     $r: Reservation (user.getReservations().size() > 20, $dis: discount)
//   then 
//     modify($r) {setDiscount($dis + 2)}
//     System.out.println("reservation number between 2 and 4");
// end

// rule "Classify Discount - Level 1"
//   agenda-group "reservation-number-discount"
//   when 
//     // TODO: isto sto i gore
//     $r: Reservation (user.getReservations().size() > 20 && user.getReservations().size() < 20, $dis: discount)
//   then 
//     modify($r) {setDiscount($dis + 2)}
//     System.out.println("reservation number between 2 and 4");
// end