package sbnz.reservation;

import pro.restommender.model.Reservation;
import pro.restommender.dto.Search;

import java.util.List;

rule "Classify Discount - Level 0"
  agenda-group "reservation-number-discount"
  when 
    // TODO: proveriti da li da ostavimo samo jednu liniju, ili ove 3, 
    // jer u uve tri koristimo napredne funkcije, a ova jedna je jednostavnija
    $r: Reservation ($user: user, $dis: discount)
    $rezervacije: List() from collect(Reservation() from $user.getReservations())
    eval($rezervacije.size() < 2)
    // $r: Reservation (user.getReservations().size() < 2)
  then 
    modify($r) {setDiscount($dis + 5)}
    System.out.println("reservation number lt 2");
end

rule "Classify Discount - Level 1"
  agenda-group "reservation-number-discount"
  when 
    // TODO: isto sto i gore
    $r: Reservation (user.getReservations().size() >= 2 && user.getReservations().size() < 4, $dis: discount)
  then 
    modify($r) {setDiscount($dis + 10)}
    System.out.println("reservation number between 2 and 4");
end

rule "Classify Discount - Level 2"
  agenda-group "reservation-number-discount"
  when 
    // TODO: isto sto i gore
    $r: Reservation (user.getReservations().size() >= 4, $dis: discount)
  then 
    modify($r) {setDiscount($dis + 15)}
    System.out.println("reservation number gt 4");
end

rule "Classify Discount - number of persons lt 4"
  agenda-group "reservation-number-discount"
  no-loop
  when 
    $search: Search(numOfPersons < 4)
    $r: Reservation($discount: discount)
  then 
    modify($r) { setDiscount($discount + 2); }
end

rule "Classify Discount - number of persons is 4"
  agenda-group "reservation-number-discount"
  no-loop
  when 
    $search: Search(numOfPersons == 4)
    $r: Reservation($discount: discount)
  then 
    modify($r) { setDiscount($discount + 3); }
end

rule "Classify Discount - number of persons gt 4"
  agenda-group "reservation-number-discount"
  no-loop
  when 
    $search: Search(numOfPersons > 4)
    $r: Reservation($discount: discount)
  then 
    modify($r) { setDiscount($discount + 4); }
end
