package sbnz;

import pro.restommender.model.Reservation;
import pro.restommender.model.AuthenticatedUser;
import pro.restommender.dto.Search;
import pro.restommender.event.ReservationEvent;

rule "More than 5 new reservations in an hour from one user"
    when
        $user: AuthenticatedUser(blocked == false)
        $t1: ReservationEvent($cId: userId)
        Number(intValue >= 5) from accumulate(
            $t2: ReservationEvent(
                this != $t1,
                userId == $cId,
                this meets[5m] $t1
            ),
            count($t2)
        )
    then
        System.out.println("CEP --------------------------- Vise od 5 pokusaja dodavanja rezervacija");
        modify($user) {setBlocked(true)}
end
