package sbnz;

import pro.restommender.model.AuthenticatedUser;
import pro.restommender.event.LoginEvent;
import java.util.Date;

rule "More than 5 bad logins"
    when
        $user: AuthenticatedUser(blocked == false, $userIdAlek: id)
        $t1: LoginEvent($cId: userId, userId == $userIdAlek)
        Number(intValue >= 5) from accumulate(
            $t2: LoginEvent(
                this != $t1,
                userId == $cId
            ) over window:time(5m),
            count($t2)
        )
    then
        System.out.println("CEP --> Vise od 5 pokusaja logovanja.");
        modify($user) {setBlocked(true)}
        modify($user) {setBlockedDate(new Date())}
end
