package sbnz;

import pro.restommender.model.Reservation;
import pro.restommender.model.AuthenticatedUser;
import pro.restommender.dto.Search;
import pro.restommender.event.SearchEvent;
import java.util.Date;

rule "More than 5 searches in 5 minutes from one user"
    when
        $user: AuthenticatedUser(blocked == false, $userIdVeljko: id)
        $t1: SearchEvent($cId: userId, userId == $userIdVeljko)
        Number(intValue >= 5) from accumulate(
            $t2: SearchEvent(
                this != $t1,
                userId == $cId,
                this meets[5m] $t1
            ),
            count($t2)
        )
    then
        System.out.println("CEP --> Isti korisnik vise od 5 pretraga u 5 minuta.");
        modify($user) {setBlocked(true)}
        modify($user) {setBlockedDate(new Date())}
end
