package sbnz.reservation;

import pro.restommender.model.Reservation;
import pro.restommender.model.Rule;
import pro.restommender.dto.Search;

import java.util.List;

// ------------------------Pravila prvog nivoa------------------------
// -------------------------------------------------------------------

rule "Classify Discount - Level 1 - D1 => X1"
  agenda-group "reservation-number-discount"
  when 
    // TODO: proveriti da li da ostavimo samo jednu liniju, ili ove 3, 
    // jer u uve tri koristimo napredne funkcije, a ova jedna je jednostavnija
    $r: Reservation ($user: user, $dis: discount)
    $rule: Rule(rule == "")
    $rezervacije: List() from collect(Reservation() from $user.getReservations())
    eval($rezervacije.size() < 2)
    // $r: Reservation (user.getReservations().size() < 2)
  then 
    modify($r) {setDiscount($dis + 5)}
    modify($rule) {setRule("D1")}
    System.out.println("reservation number lt 2");
end

rule "Classify Discount - Level 1 - D2 => X2"
  agenda-group "reservation-number-discount"
  when 
    // TODO: isto sto i gore
    $r: Reservation (user.getReservations().size() >= 2 && user.getReservations().size() < 4, $dis: discount)
    $rule: Rule(rule == "")
  then 
    modify($r) {setDiscount($dis + 10)}
    modify($rule) {setRule("D2")}
    System.out.println("reservation number between 2 and 4");
end

rule "Classify Discount - Level 1 - D3 => X3"
  agenda-group "reservation-number-discount"
  when 
    // TODO: isto sto i gore
    $r: Reservation (user.getReservations().size() >= 4, $dis: discount)
    $rule: Rule(rule == "")
  then 
    modify($r) {setDiscount($dis + 15)}
    modify($rule) {setRule("D3")}
    System.out.println("reservation number gt 4");
end

// ------------------------Pravila drugog nivoa------------------------
// --------------------------------------------------------------------

rule "Classify Discount - Level 2 - D4 => X4"
  agenda-group "reservation-number-discount"
  no-loop
  when 
    $search: Search(numOfPersons != 0)
    $r: Reservation($discount: discount)
    $rule: Rule(rule == "D1")
  then 
    modify($r) { setDiscount($discount + 2); }
    modify($rule) {setRule("D4")}
    System.out.println("Classify Discount - Level 2 - D4 => X4");
end

rule "Classify Discount - Level 2 - D5 => X5"
  agenda-group "reservation-number-discount"
  no-loop
  when 
    $search: Search(numOfPersons != 0)
    $r: Reservation($discount: discount)
    $rule: Rule(rule == "D2")
  then 
    modify($r) { setDiscount($discount + 3); }
    modify($rule) {setRule("D5")}
    System.out.println("Classify Discount - Level 2 - D5 => X5");
end

rule "Classify Discount - Level 2 - D6 => X6"
  agenda-group "reservation-number-discount"
  no-loop
  when 
    $search: Search(numOfPersons != 0)
    $r: Reservation($discount: discount)
    $rule: Rule(rule == "D3")
  then 
    modify($r) { setDiscount($discount + 4); }
    modify($rule) {setRule("D6")}
    System.out.println("Classify Discount - Level 2 - D6 => X6");
end

// ------------------------Pravila treceg nivoa------------------------
// --------------------------------------------------------------------

rule "Classify Discount - Level 3 - D7 => X7"
  agenda-group "reservation-number-discount"
  when 
    // TODO: isto sto i gore
    $r: Reservation (user.getReservations().size() >= 10 && user.getReservations().size() < 15, $dis: discount)
    $rule: Rule(rule == "D4")
  then 
    modify($r) {setDiscount($dis + 2)}
    modify($rule) {setRule("D7")}
    System.out.println("Classify Discount - Level 3 - D7 => X7");
end

rule "Classify Discount - Level 3 - D8 => X8"
  agenda-group "reservation-number-discount"
  when 
    // TODO: isto sto i gore
    $r: Reservation (user.getReservations().size() >= 15 && user.getReservations().size() < 20, $dis: discount)
    $rule: Rule(rule == "D5")
  then 
    modify($r) {setDiscount($dis + 3)}
    modify($rule) {setRule("D8")}
    System.out.println("Classify Discount - Level 3 - D8 => X8");
end

rule "Classify Discount - Level 3 - D9 => X9"
  agenda-group "reservation-number-discount"
  when 
    // TODO: isto sto i gore
    $r: Reservation (user.getReservations().size() >= 20, $dis: discount)
    $rule: Rule(rule == "D6")
  then 
    modify($r) {setDiscount($dis + 4)}
    modify($rule) {setRule("D9")}
    System.out.println("Classify Discount - Level 3 - D9 => X9");
end