package sbnz.reservation;

import pro.restommender.model.Reservation;
import pro.restommender.dto.Search;

import java.util.List;

// ------------------------Pravila prvog nivoa------------------------
// -------------------------------------------------------------------

rule "Classify Discount - Level 1 - D1 => X1"
  agenda-group "reservation-number-discount"
  when 
    $r: Reservation ($user: user, $dis: discount, discount == 0)
    $rezervacije: List() from collect(Reservation() from $user.getReservations())
    eval($rezervacije.size() < 2)
  then 
    modify($r) {setDiscount($dis + 5)}
    System.out.println("Level 1 - discount was: 0, discount is: 5");
end

rule "Classify Discount - Level 1 - D2 => X2"
  agenda-group "reservation-number-discount"
  when 
    $r: Reservation ($user: user, $dis: discount, discount == 0)
    $rezervacije: List() from collect(Reservation() from $user.getReservations())
    eval($rezervacije.size() >= 2 && $rezervacije.size() < 4)
  then 
    modify($r) {setDiscount($dis + 10)}
    System.out.println("Level 1 - discount was: 0, discount is: 10");
end

rule "Classify Discount - Level 1 - D3 => X3"
  agenda-group "reservation-number-discount"
  when 
    $r: Reservation ($user: user, $dis: discount, discount == 0)
    $rezervacije: List() from collect(Reservation() from $user.getReservations())
    eval($rezervacije.size() >= 4)
  then 
    modify($r) {setDiscount($dis + 15)}
    System.out.println("Level 1 - discount was: 0, discount is: 15");
end

// ------------------------Pravila drugog nivoa------------------------
// --------------------------------------------------------------------

rule "Classify Discount - Level 2 - D4 => X4"
  agenda-group "reservation-number-discount"
  no-loop
  when 
    $search: Search(numOfPersons != 0)
    $r: Reservation($discount: discount, discount == 5)
  then 
    modify($r) { setDiscount($discount + 2); }
    System.out.println("Level 2 - discount was: 5, discount is: 7");
end

rule "Classify Discount - Level 2 - D5 => X5"
  agenda-group "reservation-number-discount"
  no-loop
  when 
    $search: Search(numOfPersons != 0)
    $r: Reservation($discount: discount, discount == 10)
  then 
    modify($r) { setDiscount($discount + 3); }
    System.out.println("Level 2 - discount was: 10, discount is: 13");
end

rule "Classify Discount - Level 2 - D6 => X6"
  agenda-group "reservation-number-discount"
  no-loop
  when 
    $search: Search(numOfPersons != 0)
    $r: Reservation($discount: discount, discount == 15)
  then 
    modify($r) { setDiscount($discount + 4); }
    System.out.println("Level 2 - discount was: 15, discount is: 19");
end

// ------------------------Pravila treceg nivoa------------------------
// --------------------------------------------------------------------

rule "Classify Discount - Level 3 - D7 => X7"
  agenda-group "reservation-number-discount"
  when 
    $r: Reservation ($user: user, $dis: discount, discount == 19)
    $rezervacije: List() from collect(Reservation() from $user.getReservations())
    eval($rezervacije.size() >= 10 && $rezervacije.size() < 15)
  then 
    modify($r) {setDiscount($dis + 2)}
    System.out.println("Level 3 - discount was: 19, discount is: 21");
end

rule "Classify Discount - Level 3 - D8 => X8"
  agenda-group "reservation-number-discount"
  when 
    $r: Reservation ($user: user, $dis: discount, discount == 19)
    $rezervacije: List() from collect(Reservation() from $user.getReservations())
    eval($rezervacije.size() >= 15 && $rezervacije.size() < 20)
  then 
    modify($r) {setDiscount($dis + 3)}
    System.out.println("Level 3 - discount was: 19, discount is: 22");
end

rule "Classify Discount - Level 3 - D9 => X9"
  agenda-group "reservation-number-discount"
  when 
    // $r: Reservation (user.getReservations().size() >= 20, $dis: discount, discount == 19)

    $r: Reservation ($user: user, $dis: discount, discount == 19)
    $rezervacije: List() from collect(Reservation() from $user.getReservations())
    eval($rezervacije.size() >= 20)
  then 
    modify($r) {setDiscount($dis + 4)}
    System.out.println("Level 3 - discount was: 19, discount is: 23");
end