package sbnz;

import pro.restommender.model.Restaurant;
import pro.restommender.model.Reservation;
import pro.restommender.model.RelevantRestaurants;
import pro.restommender.dto.Search;
import java.util.List;

/*
    Proveravamo da li imamo bar 2 restorana sa ocenom 0 do 3.
    Ako imamo setujemo dodatni popust na rezervaciju koji je jendak
    sumi ocena pronadjenih restorana puta 0.2.
*/
rule "Classify Restaurant with rate - from 0 to 3"
  no-loop
  agenda-group "rate"
  when 
    $search: Search (rate < 3.0)
    $res: Reservation ($dis: discount)
    $rr: RelevantRestaurants($restaurants: relevantRestaurants)
    $num: Double(intValue >= 1) from accumulate(
        Restaurant(
            rate >= 0.0 && rate < 3.0,
            $r: rate
        ) from $restaurants,
        sum($r)
    )
  then 
    modify($res) { setDiscount($dis + ($num*0.2)) }
    System.out.println("0-3 Add to reservation discount: " + ($num*0.2));
end

/*
    Proveravamo da li imamo bar 2 restorana sa ocenom 3 do 5.
    Ako imamo setujemo dodatni popust na rezervaciju koji je jendak
    sumi ocena pronadjenih restorana puta 0.4.
*/
rule "Classify Restaurant with rate - from 3 to 5"
  no-loop
  agenda-group "rate"
  when
    $search: Search (rate >= 3.0)
    $res: Reservation ($dis: discount)
    $rr: RelevantRestaurants($restaurants: relevantRestaurants)
    $num: Double(intValue >= 1) from accumulate(
        Restaurant(
            rate >= 3.0 && rate <= 5.0,
            $r: rate
        ) from $restaurants,
        sum($r)
    )
  then 
    modify($res) { setDiscount($dis + ($num*0.4)) }
    System.out.println("3-5 Add to reservation discount: " + ($num*0.4));
end