package sbnz;

import pro.restommender.model.Restaurant;
import pro.restommender.model.RelevantRestaurants;
import pro.restommender.dto.Search;
import java.util.List;

rule "Classify Restaurant - In Center"
  agenda-group "location"
  when
    $search: Search(location <= 1)
    $restaurants: RelevantRestaurants()
    $filteredRestaurants: List() from collect(Restaurant(location <= 1) from $restaurants.getRelevantRestaurants())
  then 
    modify( $restaurants) { setRelevantRestaurants($filteredRestaurants); }
    System.out.println( "Lokacija restorana U CENTRU");
end

rule "Classify Restaurant - Near Center"
  agenda-group "location"
  when
    $search: Search(location > 1 && location <= 5)
    $restaurants: RelevantRestaurants()
    $filteredRestaurants: List() from collect(Restaurant(location > 1 && location <= 5) from $restaurants.getRelevantRestaurants())
  then 
    modify( $restaurants) { setRelevantRestaurants($filteredRestaurants); }
    System.out.println( "Lokacija restorana BLIZU CENTRA");
end

rule "Classify Restaurant - Far Away From Center"
  agenda-group "location"
  when
    $search: Search(location > 5)
    $restaurants: RelevantRestaurants()
    $filteredRestaurants: List() from collect(Restaurant(location > 5) from $restaurants.getRelevantRestaurants())
  then 
    modify( $restaurants) { setRelevantRestaurants($filteredRestaurants); }
    System.out.println( "Lokacija restorana UDALJENI OD CENTRA.");
end
