package sbnz.restaurant;

import pro.restommender.model.Restaurant;

rule "Classify Restaurant - In Center"
  agenda-group "location"
  when 
    $r: Restaurant(location <= 1 )
  then 
    System.out.println( "in center------------------" );
end

rule "Classify Restaurant - Near Center"
  agenda-group "location"
  when 
    $r: Restaurant(location > 1 && location <= 5 )
  then 
    System.out.println( "near center------------------" );
end

rule "Classify Restaurant - Far Away From Center"
  agenda-group "location"
  when 
    $r: Restaurant(location > 5 )
  then 
    System.out.println( "far away from center------------------" );
end